### ISSUE TITLE
[feature request] Automatically get project name by default OR if none provided

### ISSUE THREAD

**Issue by RonStrauss** [Teebo/scss-migrate#11]
Would be cool if the cli would automatically get the project name at first, if only one project exists in the workspace.

I saw there's a reference to a `defaultProject` in [index.ts](https://github.com/Teebo/scss-migrate/blob/763543f1256cb021d3be32c62f01e7ac9ee22e33/src/scss-migrate/index.ts#L16), so i assume it was in the plan.

I could try to work on it, but I don't have much experience with angular or npm modules..,

Should I try regardless?

**Comment by Teebo** [comment]
Hi, yeah that's a good idea.
It'd be great if you'd try.
