### ISSUE TITLE
Error 'Not a valid Angular CLI project' when `defaultProject` is missed in angular.json

### ISSUE THREAD

**Issue by AlexElin** [Teebo/scss-migrate#9]
Error 'Not a valid Angular CLI project' is diplsayed
on `ng add schematics-scss-migrate` (css -> scss)
 when `defaultProject` is missed in angular.json.
 
 Since Angular v14 `defaultProject` is deprecated (see https://blog.ninja-squad.com/2022/06/02/angular-cli-14.0/).
 So, it's valid case that it absents in angular.json.
 
 Expected behavior: there's no error 'Not a valid Angular CLI project'.

**Comment by Teebo** [comment]
@AlexElin, it is resolved. Thanks
